---
apiVersion: v1
kind: ConfigMap
metadata:
  # kubectl config current-context
  name: myapp-configsmap
  # kubectl config use-context docker-desktop
  # kubectl config set-context docker-desktop --namespace=myapp-namespace
  namespace: myapp-namespace
data:
  LOCALHOST: "localhost"
  PORT: "8080"
  DB_DATABASE: "db1"
  DB_HOST: "mysql"
  DB_USERNAME: "user1"
  MEMCACHED_SERVER: "memcached"
  MEMCACHED_PORT: "11211"
  REDIS_SERVER: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS `db1`;
    USE `db1`;
    DROP TABLE IF EXISTS `friends`;
    CREATE TABLE IF NOT EXISTS `friends` (id INT(10) unsigned NOT NULL AUTO_INCREMENT, name VARCHAR(256), age INT, gender VARCHAR(3), PRIMARY KEY (`id`));
    INSERT INTO `friends` VALUES (1, 'John Smith', 32, 'm');
    INSERT INTO `friends` VALUES (2, 'Lilian Worksmith', 29, 'f');
    INSERT INTO `friends` VALUES (3, 'Michael Rupert', 27, 'm');