---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-redis-deployment
  namespace: myapp-namespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
      tier: persistentcache
      foo: bar
  template:
    metadata:
      name: redis
      labels:
        app: myapp
        tier: persistentcache
        foo: bar
    spec:
      volumes:
      - name: myapp-redis
        persistentVolumeClaim:
          claimName: myapp-redis-pvc
      containers:
      - name: redis
        image: "bitnami/redis:6.0.16"
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/bitnami/redis/data"
          name: myapp-redis