---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: myapp-namespace
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: myapp
    tier: database