---
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
  namespace: myapp-namespace
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8443
  selector:
    app: myapp-tutorial
  type: LoadBalancer