---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-myapp-selfsigned
  namespace: myapp-namespace
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-myapp-cert
  namespace: myapp-namespace
spec:
  dnsNames:
    - myapp.c4xp.ro
  commonName: myapp.c4xp.ro
  secretName: myapp-cert-selfsign
  issuerRef:
    name: test-myapp-selfsigned